version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 30
      runas: ec2-user

  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
