spring:
  application:
    name: backend

  ai:
    openai:
      api-key: ${OPEN_AI_APIKEY}
      model: gpt-3.5-turbo

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 100
      hibernate.format_sql: true


  data:
    redis:
      host: localhost
      port: 6379

org:
  nexusscode:
    openAITTS:
      tts-endpoint: https://api.openai.com/v1/audio/speech
    openAIWhisper:
      whisper-endpoint: https://api.openai.com/v1/audio/transcriptions

saramin:
  access-key: ${SARAMIN_ACCESS_KEY}
  endpoint: https://oapi.saramin.co.kr/job-search

aws:
  s3:
    bucket-name: demo-my-testbucket-277707098184
    user-upload-path: uploads/audio
    ai-upload-path: upload/aiAudio

jwt:
  secret: your-secure-jwt-secret-key-that-is-at-least-32-bytes
  access-token-expire-minutes: 10
  refresh-token-expire-minutes: 1440


