name: CI/CD - Upload Spring Boot Package to S3 for CodeDeploy

on:
  push:
    branches: [ feat/aws-alb ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot application
        run: ./gradlew clean build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp build/libs/backend-0.0.1-SNAPSHOT.jar deploy/app.jar
          chmod +x scripts/deploy.sh
          cp appspec.yml deploy/
          cp scripts/clean.sh deploy/ 
          cp scripts/deploy.sh deploy/
          cd deploy
          zip -r ../app.zip .
      
      - name: Upload app.zip to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.AWS_S3_BUCKET }}/app-releases/app.zip --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=app-releases/app.zip,bundleType=zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
